# kubectl apply -f jhoss-palomino-28-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: jhoss-palomino-28-secret
  namespace: jhoss-palomino-28-namespace
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9qaG9zc3BhbG9taW5vYmVuaXRvX2RiOmRpbm9zYXVyaW8xMjM0QGNsdXN0ZXIwLmU1aGRjcnYubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=   # en Base64
  DATABASE_NAME: ZXh0ZXJuYWw=
  YOUTUBE_URL: aHR0cHM6Ly9hZ2UtZGV0ZWN0b3IucC5yYXBpZGFwaS5jb20=   # en Base64
  YOUTUBE_HOST: YWdlLWRldGVjdG9yLnAucmFwaWRhcGkuY29t   # en Base64
  YOUTUBE_APIKEY: MzA1NGRjYTI5NG1zaDMxMWZjYzE2ODkzY2U3NHAxN2VmMjRqc25jYmQ4ZWFkNmVkNzY=   # en Base64
  TRANSLATE_URL: aHR0cHM6Ly9kZWVwLXRyYW5zbGF0ZTEucC5yYXBpZGFwaS5jb20vbGFuZ3VhZ2UvdHJhbnNsYXRlL3Yy
  TRANSLATE_HOST: ZGVlcC10cmFuc2xhdGUxLnAucmFwaWRhcGkuY29t
  TRANSLATE_APIKEY: MWMyMzQ1NjI0YW1zaGQxMTVmNmU5NmIzMjI4MHAxYTY1NjJqc241OWIyYWMyYzRjMDc=
  TTS_URL: aHR0cHM6Ly9zdHJlYW1saW5lZC1lZGdlLXR0cy5wLnJhcGlkYXBpLmNvbS90dHM=
  TTS_HOST: c3RyZWFtbGluZWQtZWRnZS10dHMucC5yYXBpZGFwaS5jb20=
  TTS_APIKEY: MWMyMzQ1NjI0YW1zaGQxMTVmNmU5NmIzMjI4MHAxYTY1NjJqc241OWIyYWMyYzRjMDc=

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode